id: P003105
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:40:37.128499
source_metadata:
  id: bdr:W3CN6418
  title: བོད་ལུགས་གསོ་རིག་བདེ་སྲུང་ཤེས་བྱའི་དྲི་བ་དྲིས་ལན།
  author: ''
  volumes:
    02c3976c6b7f421baee37bcc735c7786:
      image_group_id: I3CN6420
      title: ''
      volume_number: 1
      total_pages: 156
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
