id: P003105
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6418
  title: བོད་ལུགས་གསོ་རིག་བདེ་སྲུང་ཤེས་བྱའི་དྲི་བ་དྲིས་ལན།
  author: ''
  volumes:
    02c3976c6b7f421baee37bcc735c7786:
      image_group_id: I3CN6420
      title: ''
      volume_number: 1
      total_pages: 156
