id: I893C2CDC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:42:40+00:00'
last_modified: '2022-06-07T17:35:32.349043+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6418
  title: བོད་ལུགས་གསོ་རིག་བདེ་སྲུང་ཤེས་བྱའི་དྲི་བ་དྲིས་ལན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    A141:
      image_group_id: I3CN6420
      title: ''
      total_pages: 156
      order: 1
      base_file: A141.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
